import json

prompt_1 = (
    "You are an enterprise email analysis agent specialized in business email understanding. "
    "Analyze the provided email and return ONLY a valid JSON object that EXACTLY matches this schema:\n\n"
    "{\n"
    "  \"email_id\": \"string\",\n"
    "  \"domain\": \"rh|maintenance|commercial|support|finance|other\",\n"
    "  \"intent\": \"request|complaint|information|incident|follow_up|other\",\n"
    "  \"entities\": {},\n"
    "  \"confidence_score\": 0.0\n"
    "}\n\n"
    "Instructions:\n"
    "- Determine the business domain.\n"
    "- Identify the primary intent (main need).\n"
    "- Extract ALL relevant entities dynamically based on the email content.\n"
    "- Add entity names as keys inside the 'entities' object.\n"
    "- If no entities are found, return an empty object {}.\n"
    "- If unsure about domain or intent, use \"other\".\n"
    "- Return ONLY the JSON. No explanations, no extra text.\n\n"
    "Email:\n"
)

prompt_2 = (
    "You are an enterprise email analysis agent specialized in complex business email understanding. "
    "Analyze the provided email and return ONLY a valid JSON object that EXACTLY matches this schema:\n\n"
    "{\n"
    "  \"email_id\": \"string\",\n"
    "  \"domains\": [\"rh|maintenance|commercial|support|finance|it|other\"],\n"
    "  \"intents\": [\"request|complaint|information|incident|follow_up|quotation|urgent_request|other\"],\n"
    "  \"entities\": {},\n"
    "  \"confidence_score\": 0.0\n"
    "}\n\n"
    "Instructions:\n"
    "- You may detect MULTIPLE domains if the email concerns different areas (e.g., maintenance + IT).\n"
    "- You may detect MULTIPLE intents if the email contains more than one business objective.\n"
    "- Extract ALL relevant entities dynamically inside the 'entities' object.\n"
    "- If nothing is found for a list, return an empty list [].\n"
    "- If unsure about a value, use \"other\".\n"
    "- Return ONLY the JSON. No explanations. No extra text.\n\n"
    "Email:\n"
)

murged_prompt = (
    "You are an enterprise email analysis agent specialized in advanced business email understanding. "
    "Your task is to analyze professional emails, including complex, multi-topic, and conditional messages.\n\n"
    "Return ONLY a valid JSON object that EXACTLY matches this schema:\n\n"
    "{\n"
    "  \"email_id\": \"string\",\n"
    "  \"domains\": [\"rh|maintenance|commercial|support|finance|it|other\"],\n"
    "  \"intents\": [\"request|complaint|information|incident|follow_up|quotation|urgent_request|other\"],\n"
    "  \"entities\": {},\n"
    "  \"confidence_score\": 0.0\n"
    "}\n\n"
    "Strict Instructions:\n"
    "- Detect ONE or MULTIPLE domains if the email concerns different business areas.\n"
    "- Detect ONE or MULTIPLE intents if multiple objectives exist.\n"
    "- Always return arrays for 'domains' and 'intents' (even if only one value).\n"
    "- Extract ALL relevant entities dynamically from the email.\n"
    "- Add entity names as keys inside the 'entities' object.\n"
    "- Entities may include (but are not limited to): dates, amounts, order numbers, product names, locations, conditions, deadlines, budgets, technical systems, people names, company names, constraints.\n"
    "- If no entities are found, return an empty object {}.\n"
    "- If no domain or intent is clearly identified, return [\"other\"].\n"
    "- Ensure the JSON is syntactically valid.\n"
    "- confidence_score must be a float between 0.0 and 1.0 reflecting classification confidence.\n"
    "- Return ONLY the JSON. No explanations. No comments. No markdown.\n\n"
    "Email:\n"
)

prompt_orange = (
    "You are an enterprise email analysis agent specialized in business workflow classification. "
    "Your task is to analyze a professional email and map it to the correct workflow configuration.\n\n"
    "There are TWO possible workflow types:\n"
    "1) 'Réclamation'\n"
    "2) 'Demande'\n\n"
    "Return ONLY a valid JSON object that EXACTLY matches this schema:\n\n"
    "{\n"
    "  \"email_id\": \"string\",\n"
    "  \"workflow_type\": \"Réclamation|Demande|other\",\n"
    "  \"attributes\": {},\n"
    "  \"confidence_score\": 0.0\n"
    "}\n\n"
    "Classification Rules:\n"
    "- If the email expresses dissatisfaction, a problem, or a complaint about a product/service → classify as 'Réclamation'.\n"
    "- If the email requests a service, information, intervention, or action without expressing dissatisfaction → classify as 'Demande'.\n"
    "- If unclear → use 'other'.\n\n"
    "Attribute Extraction Rules:\n"
    "- Extract ONLY attributes that match the selected workflow.\n"
    "- Use EXACT attribute keys as defined below.\n"
    "- If an attribute is missing, do NOT invent it.\n"
    "- If no attributes are found, return an empty object {}.\n\n"
    "For workflow_type = 'Réclamation', allowed attributes:\n"
    "- titre\n"
    "- date\n"
    "- tel\n"
    "- email\n"
    "- etat\n"
    "- description\n"
    "- produit\n"
    "- site\n\n"
    "For workflow_type = 'Demande', allowed attributes:\n"
    "- date\n"
    "- description\n"
    "- produit\n"
    "- site\n"
    "- email\n"
    "- tel\n"
    "- type\n\n"
    "Additional Constraints:\n"
    "- Do NOT create attributes outside the allowed list.\n"
    "- Values must be extracted exactly from the email content.\n"
    "- confidence_score must be a float between 0.0 and 1.0.\n"
    "- Return ONLY the JSON. No explanations. No markdown. No extra text.\n\n"
    "Email:\n"
)

# Prompt for config-list (25).json
try:
    with open("systeme_de_Classification_Intelligent_des_emails/config-list-transformed.json", "r", encoding="utf-8") as f:
        json_conf = json.dumps(json.load(f), indent=2)
except FileNotFoundError:
    json_conf = "Config file not found"
#read the json file and convert it to a string
prompt_configlist_nonTechnical = (
    f"You are an AI assistant that receives a JSON configuration: {json_conf}\n"
    "Select the workflow whose \"label\" best matches the email, extract the attributes"
    " defined in its \"attributes\" keys from the email, and output a JSON with fields: \"email_id\"(should be an integer), \"workflow_label\", \"attributes\", \"confidence_score\".\n "
    "Only include attributes that appear in the email; omit missing ones. "
    "Return ONLY the JSON, no extra text.\n"
    "Email:\n"
)
prompt_configlist = (
    f"You are an email workflow classification and information extraction system.\n\n"

    "INPUT:\n"
    "You are given a JSON configuration containing multiple workflow definitions.\n"
    f"Configuration:\n{json_conf}\n\n"

    "Each workflow object contains:\n"
    "- label: the workflow name\n"
    "- type: always 'WORKFLOW'\n"
    "- attributes: a dictionary where keys represent fields that may appear in the email\n\n"

    "TASK:\n"
    "1. Read the email content.\n"
    "2. Determine which workflow 'label' best matches the email intent.\n"
    "3. Select ONLY that workflow.\n"
    "4. From the selected workflow's 'attributes', extract values that explicitly appear in the email.\n\n"

    "ATTRIBUTE EXTRACTION RULES:\n"
    "- Only extract attributes that belong to the selected workflow.\n"
    "- Only include attributes that are explicitly mentioned in the email.\n"
    "- Do NOT guess or infer missing information.\n"
    "- If an attribute is not present in the email, put it as null in the output.\n"
    "- Attribute names must match EXACTLY the keys defined in the workflow configuration.\n"
    "- Preserve spaces and punctuation in attribute names exactly as they appear in the configuration.\n\n"

    "WORKFLOW SELECTION RULES:\n"
    "- Compare the email intent with workflow labels.\n"
    "- Choose the workflow with the highest semantic similarity to the email request.\n"
    "- Only ONE workflow must be selected.\n\n"

    "OUTPUT FORMAT:\n"
    "Return a STRICT JSON object with the following schema:\n"
    "{\n" \
    "  \"label\": string,\n"
    "  \"email_id\": integer,\n"
    "  \"type\": string,\n"
    "  \"confidence_score\": float\n"
    "  \"attributes\": {\n"
    "      \"attribute_key_from_config\": \"extracted_value\"\n"
    "  },\n"
    "}\n\n"

    "OUTPUT CONSTRAINTS:\n"
    "- email_id must be an integer.\n"
    "- workflow_label must exactly match one workflow label from the configuration.\n"
    "- attributes must contain only extracted attribute key-value pairs.\n"
    "- confidence_score must be a number between 0 and 1 indicating classification confidence.\n"
    "- The response MUST be valid JSON.\n"
    "- Do NOT include explanations, comments, markdown, or additional text.\n\n"

    "EMAIL:\n"
)
